language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode7.3

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-mozilla-security/rust-updates'
    packages:
      - cargo

brew_packages:
  - rust
